services:
  - type: web
    name: pennywise-backend
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11  # Adjust to match your Render Python version
    buildCommand: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      export PATH="$HOME/.cargo/bin:$PATH"
      pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
